### ISSUE TITLE
Can't call our desktop install Photos

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos-desktop#23]
<img width="511" alt="Screen Shot 2019-05-10 at 2 43 10 PM" src="https://user-images.githubusercontent.com/370259/57558322-13d81c80-7332-11e9-96fd-7a3797a6991c.png">

**Comment by carsonfarmer** [comment]
Ha. I’ll call it Textile Photos?

**Comment by andrewxhill** [comment]
👍

**Comment by carsonfarmer** [comment]
Fixed with #22
