### ISSUE TITLE
Photos Desktop on Linux?

### ISSUE THREAD

**Issue by doodlemania2** [textileio/photos-desktop#35]
Couldn't get photos desktop to work on Windows, so thought I'd try on Linux (Ubuntu 19.04) - I see there's a SNAP file but the SNAP thing in Linux says invalid format.
Also noted that Tray app doesn't work with 0.3.0 which my cafe is running, no problem, just wanted to see if I could get bootstrapped and ready! :)

**Comment by carsonfarmer** [comment]
From offline interactions, it was revealed that the snaps were in fact ok. But please also track progress on the move to a simpler, singular desktop app here: https://github.com/textileio/photos-desktop/issues/44
